spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    userName: root
    password: 123456
    url: jdbc:mysql://localhost/sell_weixin?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
